# Generated by Django 4.2.1 on 2023-05-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=150, verbose_name='Название Товара')),
                ('price', models.CharField(max_length=150, verbose_name='Цена')),
                ('description', models.TextField(max_length=200, verbose_name='Описание Техники')),
                ('publisher', models.CharField(max_length=150, null=True, verbose_name='Издатель')),
                ('data', models.DateField(null=True, verbose_name='Дата выхода')),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'verbose_name': 'Продук',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
